### ISSUE TITLE
Tracking runs -- an issue to track what I must run

### ISSUE THREAD

**Issue by msoos** [nicolasprevot/GpuShareSat#7]
Todo:
- [ ]  PLEASE ADD MORE HERE
- [ ] glucose-gpu_release-memfixed -write-stats-period-sec=-1 -max-thread-count=24 -max-memory=90000 -mem-lim=100000 -no-act-only

Scheduled (Internal number 2):
- [ ] glucose-gpu_release-memfixed -write-stats-period-sec=-1 -max-thread-count=24 -gpu-inc-reduce-db=60000 -max-memory=90000 -mem-lim=100000
- [ ] glucose-gpu_release-memfixed -write-stats-period-sec=-1 -max-thread-count=24 -gpu-first-reduce-db=2000000 -max-memory=90000 -mem-lim=100000

Scheduled (internal number 1):
- [ ] glucose-gpu_release-memfixed -write-stats-period-sec=-1 -max-thread-count=24 -max-memory=90000 -mem-lim=100000 -inc-reduce-db=200
- [ ] glucose-gpu_release-memfixed -write-stats-period-sec=-1 -max-thread-count=24 -max-memory=90000 -mem-lim=100000 -gpu-cl-decay=0.99995

Skipping due to expected MEM-outs:
- [x] glucose-syrup_static -maxnbthreads=32 -maxmemory=90000 -mem-lim=100000

Done:
- [x] glucose-gpu_release -write-stats-period-sec=-1 -max-thread-count=24 -max-memory=90000 -mem-lim=100000
- [x] glucose-syrup_static -maxnbthreads=24 -maxmemory=90000 -mem-lim=100000 
- [x] glucose-gpu_release -write-stats-period-sec=-1 -max-thread-count=24 -gpu-inc-reduce-db=20000 -max-memory=90000 -mem-lim=100000
- [x] glucose-gpu_release -write-stats-period-sec=-1 -max-thread-count=24 -max-memory=90000 -mem-lim=100000
